version: 0.0
os: linux
files:
  - source: /bin/Debug/netcoreapp3.1
    destination: /home/ubuntu/netcore
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_kestrel_service.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_kestrel_service.sh
      timeout: 300
      runas: root