# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
phases:
  pre_build:
    commands:
      - /usr/local/bin/dotnet-install.sh
      - dotnet restore
  build:
    commands:
      - dotnet build --configuration Debug --no-restore
      - dotnet test --no-restore --verbosity normal
      - buildExitCode=$?
    finally:
      - |
        if [ "$buildExitCode" -ne 0 ]; then
          badge_status=failing
          badge_colour=red
        else
          badge_status=passing
          badge_colour=green
        fi
      - curl -s "https://img.shields.io/badge/build-$badge_status-$badge_colour.svg" > build-main.svg
      - aws s3 cp build-main.svg s3://esyspki-pipelineassets/badges/build-main.svg --cache-control no-cache
  post_build:
    commands:
      - rm -rf bin/Debug/net6.0/ca
      - rm -rf bin/Debug/net6.0/ts
artifacts:
  files:
    - bin/Debug/net6.0/**/*
    - scripts/**/*
    - appspec.yml