# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
phases:
  pre_build:
    commands:
      - /usr/local/bin/dotnet-install.sh
      - dotnet restore
  build:
    commands:
      - dotnet build --configuration Debug --no-restore
      - dotnet test --no-restore --verbosity normal
  post_build:
    commands:
      - rm -rf bin/Debug/net6.0/ca
      - rm -rf bin/Debug/net6.0/ts
artifacts:
  files:
    - bin/Debug/net6.0/**/*
    - scripts/**/*
    - appspec.yml